<?php

namespace app\tests\models;

use app\models\Setting;
use app\tests\AppTestCase;

class SettingTest extends AppTestCase
{


    public function testCRUD()
    {
        $model = new Setting([
            'key' => 'foo',
            'value' => ['foo'=>'bar'],
        ]);

        static::assertTrue($model->save());

        $model = Setting::find()->where(['key'=>'foo'])->one();
        static::assertSame($model->value, ['foo'=>'bar']);

        $model->value = true;
        static::assertTrue($model->save());
        $model = Setting::find()->where(['key'=>'foo'])->one();
        static::assertTrue($model->value);

    }

    public function testGet()
    {
        $model = new Setting([
            'key' => 'foo',
            'value' => ['foo'=>'bar'],
        ]);

        static::assertTrue($model->save());

        static::assertSame(
            ['foo'=>'bar'],
            Setting::get('foo')
        );
    }

    protected function setUp()
    {
        parent::setUp();
        Setting::getDb()->createCommand('TRUNCATE TABLE ' . Setting::tableName())->execute();
    }

    protected function tearDown()
    {
        Setting::getDb()->createCommand('TRUNCATE TABLE ' . Setting::tableName())->execute();
        parent::tearDown(); // TODO: Change the autogenerated stub
    }
}